### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by Shatur** [Leafwing-Studios/petitset#18]
Consider the following `Cargo.toml`:

```toml
[package]
name = "test_set"
version = "0.1.0"
edition = "2021"

[dependencies]
toml_edit = { version = "0.14", features = ["easy"] }
serde = "1.0"
petitset = {version = "0.2", features = ["serde_compat"]}
```

and the following code with `HashSet`:

```rust
use std::collections::HashSet;

use serde::Serialize;

#[derive(Serialize)]
struct Bar {
    foo: HashSet<Foo>,
}

#[derive(Serialize, Hash, PartialEq, Eq, Clone, Copy)]
enum Foo {
    #[serde(rename = "hello")]
    Hello,
}

fn main() {
    let mut foo = HashSet::new();
    foo.insert(Foo::Hello);
    let bar = Bar {
        foo,
    };
    println!("{}", toml_edit::ser::to_string(&bar).unwrap());
}
```

It prints `foo = ["hello"]`.

But with `PetitSet`:
```rust
use petitset::PetitSet;
use serde::Serialize;

#[derive(Serialize)]
struct Bar {
    foo: PetitSet<Foo, 3>,
}

#[derive(Serialize, Hash, PartialEq, Eq, Clone, Copy)]
enum Foo {
    #[serde(rename = "hello")]
    Hello,
}

fn main() {
    let mut foo = PetitSet::new();
    foo.insert(Foo::Hello);
    let bar = Bar {
        foo,
    };
    println!("{}", toml_edit::ser::to_string(&bar).unwrap());
}
```

it prints nothing. Is this expected?
